server:
  port: 8010

spring:
  application:
    name: order

  datasource:
    name: orderingsystem
    url: jdbc:mysql://localhost:3306/orderingsystem?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mapping/*.xml
#  type-aliases-package: classpath*:com.xzq.entity